twigstan/twigstan

src/PHPStan/Collector/ContextFromReturnedArrayWithTemplateAttributeCollector.php
while the previous return type was correct, it did not explicitly state/protect you from someone changing the collector and make it return a empty array.
thats a major problem which can happen, and I want to make sure this error will not bite you, like it did in my projects.
for in-detail context see https://github.com/phpstan/phpstan/discussions/11701#discussioncomment-10660711
=> Make Collector return type more explicit

src/PHPStan/Analysis/ErrorFilter.php
It's perfectly fine to do `a == b ? 'yes' : 'no'` in Twig.
=> Ignore `equal.notAllowed` identifier

.php-cs-fixer.php, src/Twig/TwigFactory.php
Added `no_unused_imports` rule to the PHP CS Fixer configuration.
=> Remove unused import and update CS fixer config

src/Finder/FilesFinder.php, tests/Finder/FilesFinderTest.php
Added a check in FilesFinder to return an empty array if no paths are given, avoiding exception at runtime.
Updated the test suite to include a case for this scenario to ensure correct functionality.
=> Fix FilesFinder find method with no path are provided.

config/phpstan.neon, phpstan-baseline.neon, src/PHPStan/DynamicReturnType/TypeHintReturnType.php, src/PHPStan/TypeSpecifying/VariableExistsExtension.php, src/Processing/Compilation/TwigVisitor/SimpleNameExpression.php, stubs/functions.php, tests/EndToEnd/RenderPoints/optionality.html.twig, tests/EndToEnd/Types/is_defined.twig
The previous implementation to check if a variable exists was flawed.
This is now solved with a VariableExistsExtension.
=> Fix `is defined` conditions

.editorconfig, config/application.neon, src/DependencyInjection/SchemaFactory.php, tests/twigstan.neon, twigstan.neon.dist
The configuration is for TwigStan only. So there is no point in having a `twigstan` level.
Before, this ran as a PHPStan Extension. There it made sense.
=> Remove `twigstan` configuration level

config/application.neon, config/phpstan.neon, src/Application/AnalyzeCommand.php, src/Application/PHPStanRunner.php, src/DependencyInjection/SchemaFactory.php, tests/twigstan.neon, twigstan.neon.dist
We should use the already existing PHPStan configuration from the project.
This way, we use the same settings (like level and extensions).
TwigStan only needs a few modifications to run.
Also added a phpstan.memoryLimit option.
Fixes #12
=> Add `phpstan.configurationFile` and `phpstan.memoryLimit` options

src/PHPStan/AnalysisResultToJson.php, src/PHPStan/Collector/BlockContextCollector.php, src/PHPStan/Collector/ExportingCollector.php, src/PHPStan/Collector/TemplateContextCollector.php
Since we run in the PHPStan configuration of the user, there might be many more collectors.
We don't need that data.
=> Optimize analysis to json

config/application.neon, src/Application/AnalyzeCommand.php, src/Application/PHPStanRunner.php, src/Application/TwigStanError.php, src/DependencyInjection/SchemaFactory.php, src/Error/Baseline/BaselineDumper.php, src/Error/Baseline/NeonBaselineDumper.php, src/Error/BaselineError.php, src/Error/BaselineErrorFilter.php, src/Error/ErrorCollapser.php, src/Error/ErrorFilter.php, src/Error/ErrorToSourceFileMapper.php, src/Error/ErrorTransformer.php, src/Error/IgnoreError.php, src/PHPStan/Analysis/AnalysisResultFromJsonReader.php, src/PHPStan/Analysis/Error.php, tests/Baseline/BaselineTest.php, tests/Baseline/baseline.neon, tests/Baseline/errors.json, tests/Baseline/expected.neon, tests/Baseline/homepage.html.twig, tests/Baseline/layout.html.twig, tests/Baseline/twigstan.neon, tests/EndToEnd/AbstractEndToEndTestCase.php, tests/ErrorHelper.php, tests/twigstan.neon, twigstan-baseline.neon
This introduces a basic baseline functionality similar to PHPStan. Except that it uses the `baselineErrors` key in the configuration.
You can use --generate-baseline to generate the baseline and include that.
There is a `reportUnmatchedIgnoredErrors` option to control what should happen when the baseline error does not match.
Note that `reportUnmatchedIgnoredErrors` does not yet work for `ignoreErrors`.
Closes #18
Fixes #9
=> Baseline functionality

config/phpstan.neon, src/Application/AnalyzeCommand.php, src/PHPStan/Collector/ContextFromTwigIncludeCallCollector.php, tests/EndToEnd/Include/footer.twig, tests/EndToEnd/Include/include_block.twig, tests/EndToEnd/Include/include_function.twig
Whenever you include a template inside a Twig template, we can collect the
context that is passed to the template.
We can then inject this into the compiled template so that we have type information there too.
This is still limited, as this currently only collects the variables defined in the template
that includes it.
We should think about how to get the context that is passed from the controller. Maybe this will
require another PHPStan run.
=> Collect context for include calls in Twig

composer.json, composer.lock, src/Processing/Compilation/PhpVisitor/InlineBlocksVisitor.php, src/Processing/Compilation/PhpVisitor/RefactorLoopClosureVisitor.php, src/Processing/Compilation/PhpVisitor/RemoveBlockMethodsVisitor.php, src/Processing/Compilation/PhpVisitor/RemoveImportMacroVisitor.php, src/Processing/Compilation/PhpVisitor/RemoveImportsVisitor.php, src/Processing/Compilation/PhpVisitor/RemoveParentYieldVisitor.php, src/Processing/Compilation/PhpVisitor/ReplaceWithSimplifiedTwigTemplateVisitor.php, src/Processing/Flattening/PhpVisitor/InlineParentTemplateVisitor.php, src/Processing/ScopeInjection/PhpVisitor/PhpToTemplateLinesNodeVisitor.php
Fixes #62
Before, we had to use PHP Parser 4 because the project was set up as a PHPStan extension.
Since the architecture changed, we can freely change this to whatever version we want.
=> Bump nikic/php-parser to ^5.1.0

castor.php, src/Processing/Compilation/PhpVisitor/UnsetParentAfterForLoopVisitor.php, src/Processing/Compilation/TwigCompiler.php
Until we have https://github.com/twigphp/Twig/pull/4404, we need to manually unset the _parent variable
when the for loop finishes.
Otherwise PHPStan spends a lot of time analyzing loop in loops.
See https://github.com/phpstan/phpstan/issues/11890
=> Unset _parent variable after for loop in Twig 3

config/application.neon, src/Application/AnalyzeCommand.php, src/Config/ConfigBuilder.php, src/DependencyInjection/ContainerFactory.php, src/Error/Baseline/PhpBaselineDumper.php, src/Error/BaselineError.php, src/Error/BaselineErrorFilter.php, src/Processing/Compilation/PhpVisitor/ReplaceWithSimplifiedTwigTemplateVisitor.php, tests/Baseline/baseline.php, tests/Baseline/expected.php
By storing the canonicalized filename we easily compare it against the reported error.
=> Use canonicalized Twig filename in Baseline

.github/workflows/ci.yaml, castor.php, phpstan-local.neon, phpstan.neon
But only enable this locally.
We don't want CI to fail on this unexpectedly.
https://github.com/staabm/phpstan-todo-by?tab=readme-ov-file#issue-tracker-key-support
=> Enable phpstan-todo-by issue tracker

.twig-cs-fixer.php, tests/EndToEnd/Include/include_block.twig
This was accidentally fixed by Twig CS Fixer.
=> Switch back to deprecated include block

config/phpstan.analyze-twig-templates.neon, config/phpstan.collect-twig-render-points.neon, src/Application/AnalyzeCommand.php, src/Processing/Compilation/CompilationResult.php, src/Processing/Compilation/CompilationResultCollection.php, src/Processing/Compilation/Parser/TwigNodeParser.php, src/Processing/Compilation/TwigCompiler.php, src/Processing/Flattening/FlatteningResult.php, src/Processing/Flattening/FlatteningResultCollection.php, src/Processing/Flattening/TwigFlattener.php, src/Processing/ScopeInjection/ScopeInjectionResult.php, src/Processing/ScopeInjection/ScopeInjectionResultCollection.php, src/Processing/ScopeInjection/TwigScopeInjector.php, src/Twig/CommentHelper.php, src/Twig/Metadata/MetadataAnalyzer.php, src/Twig/TwigFileCanonicalizer.php
Before, we would annotate the source code with canonicalized Twig names.
But this requires us to convert back and forth.
It would be easier to always work with absolute file names, same as for PHP.
=> Convert Twig names to absolute paths everywhere

.github/dependabot.yml, composer.json, composer.lock, tests/EndToEnd/Filters/errors.json, tests/EndToEnd/Filters/errors.v3.json
Because TwigStan works with the compiled code of Twig, and the compiled code
is not part of any backwards compatibility promise, we need to pin to exact Twig versions.
If we don't, we cannot guarantee that TwigStan works as expected.
Since we pin to exact versions, we need to use Dependabot to update Twig.
=> Require exact Twig versions

composer.json, composer.lock
This is part of core and therefore redundant.
=> Remove ext-hash dependency

src/Processing/Compilation/PhpVisitor/RemoveLineNumberFromGetAttributeCallVisitor.php, src/Processing/Compilation/TwigCompiler.php, tests/EndToEnd/GetAttribute/narrowing.twig
Type narrowing was not possible because PHPStan would not cache calls to CoreExtension::getAttribute
because the last argument was the line number. This means the cache key always changes.
=> Fix type narrowing

src/Application/AnalyzeCommand.php, src/Config/ConfigBuilder.php, src/Error/ErrorFilter.php, src/Error/Ignorable.php, src/Error/IgnoreByIdentifierWhenSourceLocationHasPrevious.php, src/Error/IgnoreError.php
This makes sure errors like below are ignored, when the template is extended:
> Call to function array_key_exists() with 'hideFooter' and array{ ... } will always evaluate to false.
=> Ignore error identifiers when source has previous location

composer.json, composer.lock
Let's see if Dependabot can update the upper bound of the range.
If it works, it would be a nice way to have some control over the supported versions.
=> Change Twig requirements to be a range of supported versions

.github/dependabot.yml, .github/workflows/ci.yaml, composer.json, composer.lock
I thought this was a nice way to guard that a newer version of Twig works, so that the CI can test it, but it doesn't work properly this way.
=> Stop bumping Twig

composer.json, composer.lock, tests/EndToEnd/RenderPoints/errors.v3.json
This fixes the location of the `{% else %}` block for `for` tags.
=> Bump Twig to 3.20
