- src/Application/AnalyzeCommand.php
- src/PHPStan/Collector/ContextFromRenderMethodCallCollector.php
- src/PHPStan/Collector/ContextFromReturnedArrayWithTemplateAttributeCollector.php
- src/PHPStan/Collector/TemplateContextCollector.php
- src/Processing/ScopeInjection/TwigScopeInjector.php
Extracted from https://github.com/twigstan/twigstan/pull/17
It will be easier if all the Collector have the same signature.
> Introduce TemplateContextCollector

- tests/EndToEnd/GetAttribute/GetAttributeTest.php
- tests/EndToEnd/Inheritance/InheritanceTest.php
- tests/EndToEnd/RenderPoints/RenderPointsTest.php
- tests/EndToEnd/Types/TypesTest.php
Hi @ruudk 
Test are not executed if they are called `testCase`.
So I renamed those files.
> Execute all tests

- src/Application/AnalyzeCommand.php
Fixes #11
Let's see which errors are reported that should be fixed.
> Do not disable extension-installer

- README.md
- composer-dependency-analyser.php
- config/phpstan.neon
- src/Application/AnalyzeCommand.php
- src/PHPStan/Collector/ContextFromControllerRenderMethodCallCollector.php
- src/PHPStan/Collector/ContextFromReturnedArrayWithTemplateAttributeCollector.php
- src/PHPStan/Collector/ContextFromTwigRenderMethodCallCollector.php
- src/Twig/TwigFileNormalizer.php
- tests/EndToEnd/RenderPoints/RenderFromAbstractController.php
- tests/EndToEnd/RenderPoints/RenderFromTwig.php
- tests/EndToEnd/RenderPoints/errors.json
- tests/EndToEnd/RenderPoints/render.html.twig
> Implement ContextFromTwigRenderMethodCallCollector

- .github/workflows/ci.yaml
- composer.json
- composer.lock
We should start testing on lowest and highest.
> Add test matrix

- .github/workflows/ci.yaml
- phpstan.neon
- src/PHPStan/DynamicReturnType/GetAttributeReturnType.php
- src/Processing/Compilation/PhpVisitor/RefactorLoopClosureVisitor.php
- src/Processing/Compilation/PhpVisitor/ReplaceWithSimplifiedTwigTemplateVisitor.php
- src/Processing/Compilation/TwigCompiler.php
- tests/EndToEnd/RenderPoints/errors.json
- tests/EndToEnd/RenderPoints/errors.v3.json
- tests/EndToEnd/Types/loops.twig
- tests/ErrorHelper.php
Blocked by:
- https://github.com/twigphp/Twig/pull/4399
> Add support for Twig 4

- .github/workflows/ci.yaml
We want to run PHPStan with highest and lowest dependencies.
> Add PHPStan to matrix

- config/application.neon
- config/phpstan.neon
- src/Application/AnalyzeCommand.php
- src/Application/PHPStanRunner.php
- src/Finder/FilesFinder.php
- src/PHPStan/Analysis/AnalysisResultFromJsonReader.php
- src/PHPStan/Analysis/PHPStanAnalysisResult.php
- src/PHPStan/AnalysisResultToJson.php
- src/Processing/Compilation/PhpVisitor/ReplaceWithSimplifiedTwigTemplateVisitor.php
- src/Processing/ScopeInjection/ArrayShapeMerger.php
- src/Processing/ScopeInjection/PhpVisitor/InjectContextVisitor.php
- tests/Finder/FilesFinderTest.php
- tests/Processing/ScopeInjection/ArrayShapeMergerTest.php
- tests/twigstan.php
> Improve performance

- example/twig-loader-symfony.php
> Fetch `twig` from `test.service_container`

- .gitignore
- config/application.neon
- src/Application/PHPStanRunner.php
- src/Config/ConfigBuilder.php
- src/Config/TwigStanConfig.php
- src/DependencyInjection/ContainerFactory.php
- tests/EndToEnd/RenderPoints/AbstractCustomController.php
- tests/EndToEnd/RenderPoints/CustomControllerContextCollector.php
- tests/EndToEnd/RenderPoints/CustomRenderPointController.php
- tests/EndToEnd/RenderPoints/errors.v3.json
- tests/twigstan.php
Fixes https://github.com/twigstan/twigstan/issues/71
>  Allow registering custom TemplateContextCollector's

- src/Config/ConfigBuilder.php
Ref https://github.com/twigstan/twigstan/issues/4#issuecomment-2431930621
> Avoid macro errors

- src/Config/ConfigBuilder.php
- src/Twig/Metadata/MetadataAnalyzer.php
- tests/EndToEnd/Inheritance/dynamic_inheritance.twig
See #6
It's still not fully supported, but at least it no longer crashes.
> Handle NameExpression in MetadataAnalyzer

- composer-dependency-analyser.php
- phpstan.neon
- src/Processing/Compilation/ModifiedCompiler.php
- src/Processing/Compilation/PhpVisitor/RefactorLoopClosureVisitor.php
- src/Processing/Compilation/TwigVisitor/MarkNameExpressionAsAlwaysDefinedVisitor.php
- src/Twig/Metadata/MetadataAnalyzer.php
- src/Twig/TokenParser/AssertTypeNode.php
- src/Twig/TokenParser/AssertVariableExistsNode.php
See https://github.com/twigphp/Twig/pull/4398
> Fix compatibility with latest Twig changes

- .github/FUNDING.yml
As soon as it’s approved we switch it to the organization account.
> Switch sponsor account

- config/application.neon
- src/Application/AnalyzeCommand.php
- src/Config/ConfigBuilder.php
- src/Config/TwigStanConfig.php
- src/DependencyInjection/ContainerFactory.php
- tests/twigstan.php
Fixes https://github.com/twigstan/twigstan/issues/83
> Make `editorUrl` configurable and support relative file path

- composer.json
- composer.lock
- src/Processing/Compilation/TwigVisitor/MarkNameExpressionAsAlwaysDefinedVisitor.php
- tests/EndToEnd/Tags/TagsTest.php
- tests/EndToEnd/Tags/errors.json
- tests/EndToEnd/Tags/set.twig
Blocked by:
- https://github.com/phpstan/phpstan-src/pull/3602
> Add tests for set capture mode

- .gitattributes
previously export ignore also config/phpstan.neon file
> Fix .gitattributes path for phpstan.neon

- composer.json
- composer.lock
This will be handled in #96 later.
> Do not allow PHPStan 2.0 just yet

- composer.json
- composer.lock
- src/Processing/TemplateContext.php
- src/Processing/TemplateContextFactory.php
- src/Twig/SourceLocation.php
- tests/Processing/TemplateContextTest.php
See https://github.com/shipmonk-rnd/composer-dependency-analyser/issues/204
> Replace crc32 with hash('crc32b')

- config/phpstan.analyze-twig-templates.neon
- src/PHPStan/Rules/GetAttributeRule.php
- src/PHPStan/Visitor/AssertTypeVisitor.php
- tests/EndToEnd/GetAttribute/errors.json
- tests/EndToEnd/GetAttribute/print.twig
This rule checks when GetAttributeRule returns an ErrorType and reports an error for it.
> Introduce GetAttributeRule

- src/Application/AnalyzeCommand.php
- src/Processing/Compilation/TwigVisitor/SimpleIncludeNode.php
- src/Processing/TemplateContext.php
- tests/EndToEnd/AbstractTemplate/context.json
- tests/EndToEnd/Include/context.json
- tests/EndToEnd/Inheritance/context.json
- tests/Processing/TemplateContextTest.php
Added extra tests to assert the context is correctly collected.
> Fix handling of includes

- src/Application/AnalyzeCommand.php
- tests/EndToEnd/Bug152/Bug152Test.php
- tests/EndToEnd/Bug152/Controller.php
- tests/EndToEnd/Bug152/context.json
- tests/EndToEnd/Bug152/errors.json
- tests/EndToEnd/Bug152/homepage.twig
- tests/EndToEnd/Bug152/layout.twig
- tests/EndToEnd/Bug152/page.twig
> Analyze dependencies on second run

- src/PHPStan/Collector/BlockContextCollector.php
- src/Processing/Compilation/PhpVisitor/AddExtraLineNumberCommentVisitor.php
- tests/EndToEnd/Inheritance/Case4Controller.php
- tests/EndToEnd/Inheritance/bug_164.twig
- tests/EndToEnd/Inheritance/context.json
> Fallback to line 1 when no comments found

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/config.yml
- bin/twigstan
- phpstan.neon
- src/Application/AnalyzeCommand.php
- src/Application/VersionCommand.php
- src/DependencyInjection/ContainerFactory.php
> Add version command and bug issue template

- src/PHPStan/GetAttributeCheck.php
- tests/EndToEnd/GetAttribute/Fixtures/UserId.php
- tests/EndToEnd/GetAttribute/RenderTest.php
- tests/EndToEnd/GetAttribute/array.render.twig
- tests/EndToEnd/GetAttribute/constant_array.render.twig
- tests/EndToEnd/GetAttribute/errors.json
> Refactor how arrays are handled

- src/Processing/Compilation/TwigVisitor/MarkNameExpressionAsAlwaysDefinedVisitor.php
This broke on Twig 4 because of https://github.com/twigphp/Twig/pull/4525.
> Do not mark always_defined when is_defined_test

- src/PHPStan/GetAttributeCheck.php
- tests/EndToEnd/RenderPoints/form.html.twig
This should
closes https://github.com/twigstan/twigstan/issues/159
> Handle ArrayAccess in getAttribute

- src/Application/AnalyzeCommand.php
- src/PHPStan/Collector/BlockContextCollector.php
- src/Processing/Flattening/TwigFlattener.php
- src/Processing/ScopeInjection/PhpVisitor/InjectContextVisitor.php
- src/Processing/ScopeInjection/TwigScopeInjector.php
- src/Processing/TemplateContext.php
- tests/EndToEnd/Bug154/Bug154Test.php
- tests/EndToEnd/Bug154/Controller.php
- tests/EndToEnd/Bug154/base.twig
- tests/EndToEnd/Bug154/context.json
- tests/EndToEnd/Bug154/errors.json
- tests/EndToEnd/Bug154/include.twig
- tests/EndToEnd/Bug154/layout.twig
- tests/EndToEnd/Bug154/page.twig
- tests/EndToEnd/Bug154/sub-include.twig
- tests/EndToEnd/Bug154/superLayout.twig
Closes https://github.com/twigstan/twigstan/issues/154
Closes https://github.com/twigstan/twigstan/issues/80
> Improve experience for included blocks or templates
